apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-migration
  template:
    metadata:
      labels:
        app: database-migration
    spec:
      containers:
        - name: database-migration
          image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/cla_backend:database-migration"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          env:
            - name: TARGET_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-11
                  key: host
            - name: TARGET_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-11
                  key: name
            - name: TARGET_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-11
                  key: user
            - name: TARGET_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-11
                  key: password
            - name: SOURCE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-10
                  key: host
            - name: SOURCE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-10
                  key: name
            - name: SOURCE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-10
                  key: user
            - name: SOURCE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-10
                  key: password
